### ISSUE TITLE
Tell Reach devs a preferred error format

### ISSUE THREAD

**Issue by jeapostrophe** [reach-sh/reach-ide#11]
Right now you are doing a noble job parsing the errors, but it would be pretty easy for us to add a command-line option and mode to produce JSON-formatted error messages for a tighter integration.

**Comment by ericglau** [comment]
I was thinking of an option to have JSON formatted error messages as well.  The information that would be needed is:
- Range with start line and character number, and ideally the end line and character number as well.  Right now as the compiler does not provide the end of the range, I just make an assumption of the current token or until the end of the line.  
- The human readable message that should be displayed.  Perhaps this could omit the "Did you mean" suggestions.
- A list of suggestions to replace the section that is highlighted by the range (if the specific error has suggestions).  For example, the "Did you mean" suggestions.  Also, an [isPreferred](https://github.com/microsoft/vscode-languageserver-node/blob/ccb894231aae0942d2cc29fd2381ccf51ac4f823/types/src/main.ts#L2384) boolean can be provided if a certain suggestion properly addresses the error.
- A label for each suggestion can be helpful as well (in case the suggestion's code is too long to be used as a label)

Another possibility might be [severity](https://github.com/microsoft/vscode-languageserver-node/blob/ccb894231aae0942d2cc29fd2381ccf51ac4f823/types/src/main.ts#L499), but does the compiler generate anything that isn't an error?

Also, if there are a number of errors such as many unbound identifiers, the compiler currently only gives an error on the first one. Can (or should) the compiler give multiple errors in these kinds of situations?

I can experiment a bit and mock up a proposed JSON format for the above if that helps.

**Comment by jeapostrophe** [comment]
Awesome, I'll look into doing this.

**Comment by ericglau** [comment]
Fixed in https://github.com/ericglau/reach-ide/pull/23, available in version 0.0.9 of the extension
