### ISSUE TITLE
Review Ethereum deployment in tutorial and check out the prototype Reach demos

### ISSUE THREAD

**Issue by jeapostrophe** [reach-sh/reach-ide#13]
In your IDE (and pitch video), you copy & paste the Ethereum bytecode & ABI and interact with them directly. The model of Reach is that your front-end program would be responsible for doing deployment and would do so programmatically. The end-to-end tests do this on a development node, but in the "real world" it would also be done by the application.

We're about to update the documentation with a walk-through of React apps that deploy and drive Reach-implemented dApps --- https://github.com/reach-sh/reach-lang/tree/master/react-examples/overview --- and they demonstrate the way we imagine this working. In particular, using the programmatic method retains the blockchain agnosticism of Reach (right now, you can deploy on Ethereum AND Algorand!)

I'd love to talk to you about this and get your perspective.

**Comment by ericglau** [comment]
Removed direct Ethereum interaction in https://github.com/ericglau/reach-ide/pull/24
