### ISSUE TITLE
Menu item references command 'reach.issue' which is not defined in the 'commands' section.

### ISSUE THREAD

**Issue by KBryan** [reach-sh/reach-ide#32]
When working with Reach IDE extension and building and running the extension project in a new Extension Development Host window. I get the following error.

Step to reproduce:
= git clone the Reach IDE project
= install necessary npm packages
= compile and run the extension within the extension development host

Expected outcome:

= I think this should create a gist file for easier reporting in the help section in the Reach discord channel.

<img width="669" alt="Screen Shot 2021-06-21 at 8 56 00 AM" src="https://user-images.githubusercontent.com/681817/122765559-a2882900-d26e-11eb-88f0-d2a49d9ba9f5.png">

**Comment by chrisnevers** [comment]
thanks for the reports, I've fixed these issues, including deleting `samples.ts` and adding the commands in the most recent commit: https://github.com/reach-sh/reach-ide/commit/bf53f490aa35ddf5a6a8b267b43de719d80c2b10
